accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
]

dashboard/urls.py
from django.urls import path, include
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index')
]

djangotemplate/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing_page.urls', namespace='landing_page')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

landing_page/urls.py
from django.urls import path, include
from . import views

app_name = 'landing_page'

urlpatterns = [
    path('', views.index, name='index')
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass

dashboard/models.py
from django.db import models

# Create your models here.

landing_page/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse

from .forms import CustomUserCreationForm
from .models import User

# Create your views here.
def login_view(request):

    #prevents access by logged in users
    if request.user.is_authenticated:
        return redirect('dashboard:index')

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('dashboard:index')
        else:
            return render(request, 'accounts/login.html', {
                'message': 'Invalid username and/or password'
            })
    elif request.method == 'GET':
        return render(request, 'accounts/login.html')

def logout_view(request):
    logout(request)
    return redirect('accounts:login')

def register_view(request):

    #prevents access by logged in users
    if request.user.is_authenticated:
        return redirect('dashboard:index')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('dashboard:index')
        else:
            #checks if username is taken
            username = request.POST['username']
            if User.objects.filter(username=username).exists():
                return render(request, 'accounts/register.html', {
                    'form': form,
                    'message': 'Username has already been taken'
                })
            #checks if email is taken
            email = request.POST['email']
            if User.objects.filter(email=email).exists():
                return render(request, 'accounts/register.html', {
                    'form': form,
                    'message': 'Email address is already in use'
                })
            password1 = request.POST['password1']
            confirm = request.POST['password2']
            if password1 != confirm:
                return render(request, 'accounts/register.html', {
                    'form': form,
                    'message': 'Passwords do not match'
                })

            return render(request, 'accounts/register.html', {
                'form': form,
                'message': 'An unknown error occured.'
                })
    elif request.method == 'GET':
        form = CustomUserCreationForm()
        return render(request, 'accounts/register.html', {'form': form})

dashboard/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):

    #if user is not logged in, redirect to home page
    if not request.user.is_authenticated:
        return redirect('accounts:login')
    
    return render(request, 'dashboard/index.html')

landing_page/views.py
from django.shortcuts import render

# Initial landing page view.
def index(request):
    return render(request, 'landing_page/index.html')


#Add other views here

accounts/templates/accounts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'landing_page/images/favicon.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'landing_page/css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'accounts/css/auth.css' %}">
    <title>django auth - {% block title%} {% endblock %}</title>
</head>
<body>
    {% block form %}
    {% endblock form %}
</body>
</html>

accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% load static %}

{% block title %}Login{% endblock title %}

{% block form %}
    <form action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}

        <h1>Log In</h1>

        {% if message %}
            <p class="error">{{ message }}</p>
        {% endif %}
        <div class="form-group">
            <p class="field-label">
                Username
            </p>
            <input type="text" name="username" id="username">
        </div>

        <div class="form-group">
            <p class="field-label">
                Password
            </p>
            <input type="password" name="password" id="password">
        </div>

        <input type="submit" value="Log In">

        <p class="dont-have">
            Don't have an account? <a href="{% url 'accounts:register' %}">Register here.</a>
        </p>
    </form>

    
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'accounts/base.html' %}
{% load static %}

{% block title %}Register{% endblock title %}

{% block form %}
    <form action="{% url 'accounts:register' %}" method="post">
        {% csrf_token %}

        <h1>Register</h1>

        {% if message %}
            <p class="error">{{ message }}</p>
        {% endif %}
        
        {% for field in form %}
            <div class="form-group">
                <p class="field-label">
                    {{ field.label }}
                </p>
                {{ field }}
            </div>
        {% endfor %}

        <input type="submit" value="Sign Up">

        <p class="dont-have">
            Already have an account? <a href="{% url 'accounts:login' %}">Login here.</a>
        </p>

    </form>

   
{% endblock %}

dashboard/templates/dashboard/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'landing_page/images/favicon.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'landing_page/css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'dashboard/css/dashboard.css' %}">
    <title>dashboard</title>
</head>
<body>
    {% block content %}
    {% endblock content %}
</body>
</html>

dashboard/templates/dashboard/index.html
{% extends 'dashboard/base.html' %}
{% load static %}


{% block content %}

<h1>Hi there, <strong>{{request.user}}</strong>. Welcome to the dashboard</h1>

This is a blank dashboard page which inherits from dashboard/base.html. It has seperate CSS from the landing page and is located at <strong>dashboard/static/dashboard/css/dashboard.css</strong>

<p><strong style="color:red;">Note: this page is login restricted and can only be accessed by logged in users.</strong></p>

<h2>Instructions</h2>

<ol>
    <li>
        There is one CSS file in this app - <strong>dashboard.css</strong>. Feel free to replace this CSS with your own custom CSS
    </li>
</ol>

<p>To log out, click <a href="{% url 'accounts:logout' %}">here</a></p>


{% endblock content %}

landing_page/templates/landing_page/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'landing_page/images/favicon.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'landing_page/css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'landing_page/css/index.css' %}">
    <title>django template</title>
</head>
<body>
    {% block content %}
    {% endblock content %}
</body>
</html>

landing_page/templates/landing_page/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Home - Brand</title>
    <link rel="stylesheet" href="../../assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="../../assets/css/Merriweather.css">
    <link rel="stylesheet" href="../../assets/css/Open%20Sans.css">
    <link rel="stylesheet" href="../../assets/fonts/font-awesome.min.css">
    <link rel="stylesheet" href="../../assets/css/aos.min.css">
    <link rel="stylesheet" href="../../assets/css/magnific-popup.min.css">
    <link rel="stylesheet" href="../../assets/css/magnific-popup.min.css">

</head>

<body id="page-top">
    <nav class="navbar navbar-light navbar-expand-lg fixed-top" id="mainNav">
        <div class="container"><a class="navbar-brand js-scroll-trigger" href="#page-top">Brand</a><button class="navbar-toggler navbar-toggler-right" data-toggle="collapse" type="button" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><i class="fa fa-align-justify"></i></button></div>
    </nav>
    <header class="text-center text-white d-flex masthead" style="background-image: url('../../assets/img/header.jpg');">
        <div class="container my-auto">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    <h1 class="text-uppercase"><strong><br><strong>WECOME TO THE HOME OF THE BEST CRYPTO PET</strong><br><br></strong></h1>
                    <hr>
                </div>
            </div>
            <div class="col-lg-8 mx-auto">
                <p class="text-faded mb-5">We&nbsp; promise to deliver on fast and reliable transactions!</p>
            </div>
        </div>
    </header>
    <section class="bg-primary" id="about">
        <div class="container">
            <div class="row">
                <div class="col offset-lg-8 text-center mx-auto">
                    <h2 class="text-white section-heading"><span style="color: rgba(var(--bs-white-rgb), var(--bs-text-opacity)) ;">introduction</span></h2>
                    <hr class="light my-4">
                    <p class="text-faded mb-4"><br>Bnbcate is the king of pets, they are the symbol of love and peace, powerful and calm and our $bnbcate community&nbsp;is&nbsp;the&nbsp;same. Bnbcate is a decentralized experiment, launched on the march 26, 2023, by the founder, BNbcate, as a fresh opportunity for those who were struggling in the midst of the biggest bear market since. Born out of trials and tribulation, the $BNBcate community is the strongest community you'll find, supportive of one another, and pushing each other towards&nbsp;success.<br><br><br><img class="rounded-circle" src="../../assets/img/WhatsApp%20Image%202023-03-18%20at%2011.30.16.jpg"></p>
                </div>
            </div>
        </div>
    </section>
    <section id="services">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">At Your Service</h2>
                    <hr class="my-4">
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-lg-3 text-center">
                    <div class="mx-auto service-box mt-5"><i class="fa fa-facebook-square fa-4x text-primary mb-3 sr-icons" data-aos="zoom-in" data-aos-duration="200" data-aos-once="true"></i>
                        <h3 class="mb-3">Facebook</h3>
                        <p class="text-muted mb-0">Coming soon</p>
                    </div>
                </div>
                <div class="col-md-6 col-lg-3 text-center">
                    <div class="mx-auto service-box mt-5"><i class="fa fa-whatsapp fa-4x text-primary mb-3 sr-icons" data-aos="zoom-in" data-aos-duration="200" data-aos-delay="200" data-aos-once="true" style="font-size: 64px;"></i>
                        <h3 class="mb-3">Whatsapp</h3>
                        <p class="text-muted mb-0">Coming soon</p>
                    </div>
                </div>
                <div class="col-md-6 col-lg-3 text-center">
                    <div class="mx-auto service-box mt-5"><i class="fa fa-telegram fa-4x text-primary mb-3 sr-icons" data-aos="zoom-in" data-aos-duration="200" data-aos-delay="400" data-aos-once="true"></i>
                        <h3 class="mb-3">Telegram</h3>
                        <p class="text-muted mb-0">Coming soon</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 text-center mx-auto">
                    <h2 class="section-heading">Let's Get In Touch!</h2>
                    <hr class="my-4">
                    <p class="mb-5">Ready to join our community and get started? That's great! You can also give us a call or send us an email and we will get back to you as soon as possible!</p>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4 text-center ml-auto"><i class="fa fa-phone fa-3x mb-3 sr-contact" data-aos="zoom-in" data-aos-duration="300" data-aos-once="true"></i>
                    <p>123-456-6789</p>
                </div>
                <div class="col-lg-4 text-center mr-auto"><i class="fa fa-envelope-o fa-3x mb-3 sr-contact" data-aos="zoom-in" data-aos-duration="300" data-aos-delay="300" data-aos-once="true"></i>
                    <p><a href="mailto:your-email@your-domain.com"><br><span style="color: rgb(33, 37, 41);">lightspeedcharleston88@gmail.com</span><br><br></a></p>
                </div>
            </div>
        </div>
    </section>
    <script src="../../assets/js/jquery.min.js"></script>
    <script src="../../assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="../../assets/js/aos.min.js"></script>
    <script src="../../assets/js/bs-init.js"></script>
    <script src="../../assets/js/jquery.easing.min.js"></script>
    <script src="../../assets/js/jquery.magnific-popup.min.js"></script>
    <script src="../../assets/js/creative.js"></script>
</body>

</html>

landing_page/templates/landing_page/index2.html
{% extends 'landing_page/base.html' %}
{% load static %}


{% block content %}

<h1>Welcome to the landing page</h1>

This is a blank landing page which inherits from landing_page/base.html. Feel free to add more routes to this app and edit the base.html file to add more content to the landing page.

<h2>Editing Instructions</h2>

<ol>
    <li>The default favicon can be found in static/landing_page/images/favicon.png. To use your own logo, simply replace favicon.png with your own image <strong>(use the same image name or edit base.html to reflect the new name).</strong></li>
    <li>
        There are two CSS files in this app - <strong>reset.css</strong> and <strong>index.css</strong>.
        <ul>
            <li>reset.css is used to reset the default CSS of the browser. I used <a href="http://meyerweb.com/eric/tools/css/reset/" target="_blank" rel="noopener noreferrer">this</a> CSS reset from Meyerweb but feel free to replace it with Normalize CSS or any other CSS reset.</li>
            <li>index.css is used to style this page. Feel free to delete this CSS file and replace it with your own.</li>
        </ul>
    </li>
</ol>

<p>To log in, click <a href="{% url 'accounts:login' %}">here</a></p>
<p>To register, click <a href="{% url 'accounts:register' %}">here</a></p>


{% endblock content %}